# Generated by Django 5.1.2 on 2024-10-22 19:14

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.car_photo_upload_to),
        ),
    ]
