# Generated by Django 5.1.2 on 2024-10-22 20:17

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=home.models.car_photo_upload_to),
        ),
    ]
