# Generated by Django 5.1.2 on 2024-10-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_photo_options_remove_photo_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
