# Generated by Django 5.1.2 on 2024-10-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
